### ISSUE TITLE
Problem with sugartensor 1.0.0

### ISSUE THREAD

**Issue by mssmkmr** [buriburisuri/speech-to-text-wavenet#44]
I am grateful your project the sugartensor.
Recently, I noticed speech-to-text-wavenet doesn't work with sugartensor 1.0.0.

train.py line 35
`seq_len = tf.not_equal(x.sg_sum(dims=2), 0.).sg_int().sg_sum(dims=1)`
is need to change to bellow.
`seq_len = tf.not_equal(x.sg_sum(axis=2), 0.).sg_int().sg_sum(axis=1)`

Thank you again for your project.

**Comment by buriburisuri** [comment]
@mssmkmr  I'm refactoring speech-to-text-wavenet. Just wait a couple of days please.

**Comment by aryachiranjeev** [comment]
i am getting error while importing sugartensor : AttributeError: module 'tensorflow' has no attribute 'core'
is there another way than using sugartensor?
